swagger: "2.0"
info:
    title: Calculator Service
    description: Service for calc numbers
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /div/{a}/{b}:
        get:
            tags:
                - calc
            summary: div calc
            operationId: calc#div
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  type: integer
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: integer
                        format: int64
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/CalcDivDivByZeroResponseBody'
            schemes:
                - http
    /multiply/{a}/{b}:
        get:
            tags:
                - calc
            summary: multiply calc
            operationId: calc#multiply
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  type: integer
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: integer
                        format: int64
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - calc
            summary: Download ./gen/http/openapi3.json
            operationId: calc#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    CalcDivDivByZeroResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: div_DivByZero_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
